services:
  - type: web
    name: justsend-backend
    env: java
    buildCommand: ./mvnw clean install -DskipTests
    startCommand: java -Dspring.profiles.active=prod -jar target/justsend-backend-0.0.1-SNAPSHOT.jar